version: "3.2"

services:
  papercups:
    image: papercups/papercups:latest
    networks:
     - papercups-net
    restart: always
    ports:
      - "3000:3000"
      - "4000:4000"
    command: sh -c "sleep 10 && /entrypoint.sh db createdb && /entrypoint.sh db migrate && echo 'running' && /entrypoint.sh run"
    depends_on:
      - db
    environment:
      # PAPERCUPS_REGISTRATION_DISABLED: "true"
      DATABASE_URL: "ecto://postgres:postgres@db/postgres"
      # PUT YOUR OWN SECRET KEYBASE HERE (MUST BE AT LEAST 64 BYTES)
      SECRET_KEY_BASE: "dvPPvOjpgX2Wk8Y3ONrqWsgM9ZtU4sSrs4l/5CFD1sLm4H+CjLU+vcuefkmnd8934jndfv8u"
      MIX_ENV: "prod"
      REQUIRE_DB_SSL: "false"
      REACT_APP_FILE_UPLOADS_ENABLED: 1
      # Replace with your domain name
      BACKEND_URL: "localhost:4000"
      REACT_APP_URL: "localhost:4000"
      FRONTEND_BASE_URL: "http://localhost:4000"
      REACT_APP_IFRAME_URL: "http://localhost:2020"
  db:
    image: postgres:alpine
    command: postgres -c log_statement=all -c log_destination=stderr
    networks:
     - papercups-net
    restart: always
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

networks:
  papercups-net:
    driver: bridge
    enable_ipv6: false
    ipam:
      driver: default
      config:
      - subnet: 172.28.0.0/16
        gateway: 172.28.0.1
    # dns:
    #   - 8.8.8.8
    #   - 1.1.1.1
